### ISSUE TITLE
Need a literal predicate to store a non-URN call number

### ISSUE THREAD

**Issue by thisismattmiller** [nypl-registry/serialization-archives#1]
nypl:callnumber until we figure it out

**Comment by saverkamp** [comment]
When would we not use urn:example:callnum:?

**Comment by thisismattmiller** [comment]
We we need to be able to go back to the original call number for something like BILLI or linking to the catalog or other places. No way of knowing where the spaces are supposed to go.

**Comment by saverkamp** [comment]
There's also bf:shelfMark 
http://bibframe.org/vocab/shelfMark.html

**Comment by saverkamp** [comment]
We will use bf:shelfMark and keep our ears open for any expressed functionality needs that bf:shelfMarkLcc or others would serve.

TODO:
- @saverkamp to add to documentation
- @thisismattmiller to add to serialization

**Comment by thisismattmiller** [comment]
Found out yesterday the bibframe documentation we were working off of is old/broken or both. shelfMark is a sub class of the Identifier Class:
http://id.loc.gov/ontologies/bibframe.html not a literal predicate.

**Comment by saverkamp** [comment]
I think our options are:
1) use bf:shelfMark with bf:ShelfMark as object (blank node)

```
<http://data.nypl.org/resources/177815004> bf:shelfMark [ 
          a bf:ShelfMark ;
          rdfs:label "JFE 01-13787" ] .
```

2) use local nypl:shelfMark with range of literal.

```
<http://data.nypl.org/resources/177815004> nypl:shelfMark "JFE 01-13787" .
```

I don't have a preference.

**Comment by saverkamp** [comment]
Per our discussion, we will use blank nodes for identifiers, notes, and add blank nodes for edm:TimeSpan. To keep it simple for now we should only allow one prov statement per blank node rather than prov on each property. 

Need issues for each:
- Identifier -- list of bf subclasses used 
- Note -- list of note types
- edm:TimeSpan -- add documentation for simple date and date range (a la DPA)

**Comment by thisismattmiller** [comment]
Example of new data structure for new blanknodes property:

```
{
    "id" : "345435-dfgsds-45345-dgfsdg"
    "objectUri" : null,
    "objectLiteral" : null,
    "objectLiteralType" : null,
    "blanknode" : {
        "rdf:type" : "bf:ShelfMark",
        "rdf:value" : "JFE-1000 6665"
    },
    "provo" : {
        "creator" : "RI",
        "created" : "2016-01-19T22:04:56.018Z",
        "source" : "data:10001",
        "recordIdentifier" : 896422
    }
}
```
